In [1]:
#Here are some packages to load.
import pandas as pd     #imported for data analysis.
import numpy as np      #Used to work with arrays, CSV file I/O (e.g. pd.read_csv)

In [2]:
#The dataset used in this demonstration is the TMDB 5000 Movie Dataset(Metadata on ~5000 movies on TMDB.
films=pd.read_csv('tmdb_5000_movies.csv')
credit=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
#This command would show us first two data mambers of the dataset
films.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
credit.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [5]:
#By this we merge the two datas by title column
films = films.merge(credit,on='title')

In [6]:
films.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [7]:
#We removed all the columns which are not required for the data analysis 
#genres
#id
#keywords
#title
#overview
#cast
#crew

films=films[['id','title','genres','keywords','overview','cast','crew']]

In [8]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
#We now check for null or dublicated data and remove them.
films.isnull().sum()

id          0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
films.dropna(inplace=True)

In [11]:
films.duplicated().sum()

0

In [12]:
films.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
#Here Keywords column is an array of dictionary and we derive the name of the keywords from it.
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantasy','Science Fiction']

In [14]:
import ast

In [15]:
#function to fetch names from the given column
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
films['genres'] = films['genres'].apply(convert)

In [17]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [18]:
films['keywords'] = films['keywords'].apply(convert)

In [19]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [20]:
#function to fetch top 3 actor/actress name from the cast.​
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [21]:
films['cast'] = films['cast'].apply(convert)
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [22]:
films['cast'] = films[ 'cast'].apply(lambda x:x[0:3])

In [23]:
#Function to fetch director name from the crew column.​
def bring_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [24]:
films['crew'] = films['crew'].apply(bring_director)

In [25]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [26]:
films['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [27]:
#We split the overview strings into list form
films['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [28]:
films['overview'] = films['overview'].apply(lambda x:x.split())

In [29]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [30]:
#Removing spaces to avoid any multiple counts 
films['genres'] = films['genres'].apply(lambda x:[i.replace(" ","") for i in x])
films['keywords'] =films['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
films['cast'] =films['cast'].apply(lambda x:[i.replace(" ","") for i in x])
films['crew'] = films['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [31]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [32]:
films['labels'] = films['overview'] + films['genres'] + films['keywords'] + films['cast'] + films['crew']

In [33]:
films.head(2)

,id,title,genres,keywords,overview,cast,crew,labels
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [34]:
#We create a new table With columns id,titlw and labels
new_table= films[['id', 'title', 'labels']]

In [35]:
new_table['labels'] = new_table['labels'].apply(lambda x:" ".join(x))

/var/folders/g1/pdsb5q1j5k1fd8sr26nv9pqh0000gn/T/ipykernel_21436/2510400238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_table['labels'] = new_table['labels'].apply(lambda x:" ".join(x))

In [36]:
 new_table.head(2)

,id,title,labels
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [37]:
import nltk

In [38]:
from nltk.stem.porter import PorterStemmer
pts = PorterStemmer()

In [39]:
def stem(text):
    p = []
    
    for i in text.split():
       p.append(pts.stem(i))
    return " ".join(p)

In [40]:
new_table['labels'] = new_table['labels'].apply(stem)

/var/folders/g1/pdsb5q1j5k1fd8sr26nv9pqh0000gn/T/ipykernel_21436/3332725252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_table['labels'] = new_table['labels'].apply(stem)

In [41]:
#VECTORISATION OF LABELS
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [42]:
vect = cv.fit_transform(new_table['labels']).toarray()

In [43]:
vect

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [44]:
vect[0]

array([0, 0, 0, ..., 0, 0, 0])

In [45]:
cv.get_feature_names()

/Users/pratibhanaik/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [46]:
#We use cosine_similarity function to calculate daistance of one movie with other movies and to compare them.
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similar = cosine_similarity(vect)

In [48]:
sorted(similar[0], reverse=True)

[1.0000000000000002,
 0.28676966733820225,
 0.26901379342448517,
 0.2605130246476754,
 0.255608593705383,
 0.25038669783359574,
 0.24511108480187255,
 0.24455799402225925,
 0.23179316248638276,
 0.23174488732966073,
 0.2278389747471728,
 0.2252817784447915,
 0.22269966704152225,
 0.21853668936906193,
 0.21239769762143662,
 0.2108663315950723,
 0.2105263157894737,
 0.20443988269091456,
 0.20437977982832192,
 0.20395079136182276,
 0.2029530274475215,
 0.2029530274475215,
 0.20277677641345318,
 0.2024645717996314,
 0.2020475485519274,
 0.1979082783981174,
 0.19767387315371682,
 0.1976738731537168,
 0.19672236884115843,
 0.1925214071641298,
 0.19134594929397597,
 0.19088542889273336,
 0.19088542889273336,
 0.19007487139298027,
 0.1892994097121204,
 0.18731716231633883,
 0.1873171623163388,
 0.18693292157876878,
 0.1860807318911967,
 0.18394180184548975,
 0.18394180184548975,
 0.1813690625275029,
 0.18074256993863339,
 0.17996850826633903,
 0.17954621161490197,
 0.1777046633277277,
 0.17699808135119718,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.1748149640244195,
 0.17292861596651865,
 0.1711905958155815,
 0.1711905958155815,
 0.17119059581558146,
 0.17040572913692198,
 0.16943474841747155,
 0.16742770563222897,
 0.16742770563222897,
 0.16692446522239718,
 0.1661625969589056,
 0.16563698349810535,
 0.16426202236672155,
 0.16222142113076254,
 0.16222142113076252,
 0.16122923187750418,
 0.16059101370939324,
 0.15907119074394446,
 0.15907119074394446,
 0.15789473684210528,
 0.15737789507292674,
 0.15609763526361567,
 0.15511334686589626,
 0.1540171257313038,
 0.15389675281277312,
 0.15389675281277312,
 0.152008377581442,
 0.152008377581442,
 0.15018785229652767,
 0.15018785229652765,
 0.14843120879858804,
 0.14808721943977307,
 0.14673479641335554,
 0.14673479641335554,
 0.14659886790209342,
 0.14601068654819693,
 0.14567913668701626,
 0.14567913668701626,
 0.14509525002200235,
 0.14509525002200235,
 0.14509525002200233,
 0.14421498760030763,
 0.1442149876003076,
 0.14350946197048198,
 0.14350946197048198,
 0.1433848336691011,
 0.1433848336691011,
 0.1433848336691011,
 0.1419745572840903,
 0.1419745572840903,
 0.14159846508095775,
 0.14159846508095775,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.14048787173725413,
 0.13977653617040256,
 0.1391037210186643,
 0.1391037210186643,
 0.13872950617564817,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13629325512727639,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13518451760896877,
 0.13518451760896877,
 0.13497638119975428,
 0.13497638119975428,
 0.13476498501489081,
 0.13369695534647594,
 0.13369695534647594,
 0.13334518676566626,
 0.13334518676566626,
 0.1324532357065044,
 0.1324532357065044,
 0.1324532357065044,
 0.13157894736842107,
 0.13124359177794215,
 0.12988108336653278,
 0.12988108336653278,
 0.12988108336653278,
 0.12977713690461004,
 0.12977713690461004,
 0.12977713690461004,
 0.12892051277806202,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12725695259515557,
 0.12725695259515557,
 0.12725695259515557,
 0.126673647984535,
 0.126673647984535,
 0.12565617248750865,
 0.12565617248750863,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12462194771917919,
 0.12361284651454937,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699313,
 0.12227899701112963,
 0.12227899701112963,
 0.12227899701112963,
 0.12166606584807191,
 0.12166606584807191,
 0.12166606584807191,
 0.12072654548783007,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.11980845957463077,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11831213107007527,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11712303424679457,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.1163350101494222,
 0.11587244366483038,
 0.11587244366483038,
 0.11551284429847784,
 0.11506355109724453,
 0.1147078669352809,
 0.1147078669352809,
 0.11470786693528087,
 0.1141270638770543,
 0.11357771260606365,
 0.11357771260606365,
 0.11295649894498103,
 0.11295649894498103,
 0.1124803176664619,
 0.1124803176664619,
 0.1124803176664619,
 0.11243619908556624,
 0.11239029738980327,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539662,
 0.11141412945539661,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11092107999698035,
 0.11092107999698035,
 0.11037769642208699,
 0.11020775375559676,
 0.11020775375559674,
 0.10968169942141637,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10936965981495178,
 0.10936965981495178,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10876595882948199,
 0.10838874619051501,
 0.10838874619051501,
 0.10838874619051501,
 0.108388746190515,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.1074861545850028,
 0.10743376064838502,
 0.1068366854693644,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.10650358071057624,
 0.10650358071057624,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10559715077387793,
 0.10559715077387793,
 0.10559715077387793,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10471347707292386,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10385162309931599,
 0.10385162309931599,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10301070542879115,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10218988991416095,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10138838820672659,
 0.101338918387628,
 0.101338918387628,
 0.10133891838762799,
 0.10060545457319173,
 0.10060545457319173,
 0.10060545457319173,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09909250441117726,
 0.09909250441117726,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.09836118442057921,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.0967301666813349,
 0.0967301666813349,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09558988911273408,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09493290614465533,
 0.09464970485606021,
 0.09464970485606021,
 0.09464970485606021,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09243423333081696,
 0.09243423333081695,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09183979479633063,
 0.09183979479633063,
 0.09183979479633061,
 0.09125667909262308,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08977310580745099,
 0.0891313035643173,
 0.08903057122447033,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08797691788472337,
 0.08749572785196143,
 0.08749572785196143,
 0.08749572785196143,
 0.08746392856766495,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08594700851870801,
 0.08594700851870801,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08321783316232578,
 0.0830812984794528,
 0.0830812984794528,
 0.0830812984794528,
 0.08240856434303293,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08175191193132876,
 0.08175191193132876,
 0.08175191193132876,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08048436365855338,
 0.08048436365855338,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07992075789278003,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.0792740035289418,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07878168645790681,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.0781166566864507,
 0.0781166566864507,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07755667343294813,
 0.07755667343294813,
 0.0770085628656519,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.07594632491572426,
 0.07577352304240824,
 0.07543142864047142,
 0.07530940414109724,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07492686492653551,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07394738666465357,
 0.07394738666465357,
 0.07394738666465357,
 0.0734718358370645,
 0.0734718358370645,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07209840939145001,
 0.07209840939145001,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07038153430777869,
 0.07038153430777869,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.0672863110252489,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06657426652986062,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06578947368421054,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06521546507260247,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06424925662032356,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,

In [49]:
similar[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [50]:
new_table['labels']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: labels, Length: 4806, dtype: object

In [51]:
#A function which will return the name of the 5 films with maximum similarity with the given movie.
def Suggest(film):
    films_ind =  new_table[new_table['title'] ==film].index[0]
    distances = similar[films_ind]
    films_list = sorted(list(enumerate(distances)), reverse=True,key=lambda x:x[1])[1:6]
    
    for i in films_list:
        print(new_table.iloc[i[0]].title)

In [52]:
Suggest('The Hobbit: The Desolation of Smaug')

The Hobbit: An Unexpected Journey
The Hobbit: The Battle of the Five Armies
The Lord of the Rings: The Two Towers
The Lord of the Rings: The Fellowship of the Ring
Reign of Fire

In [53]:
import pickle

In [59]:
pickle.dump(new_table,open('films.pkl','wb'))

In [60]:
pickle.dump(new_table.to_dict(),open('films_dict.pkl','wb'))

In [57]:
new_table['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [58]:
pickle.dump(similar,open('similarity.pkl','wb'))